---
services:
  fastapi:
    image: $DOCKER_FASTAPI_IMAGE
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ai-models:/app/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    #add GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  ai-models:
